export const GET_EMPLOYEES_LIST_REQUEST = "GET EMPLOYEES LIST REQUEST";
export const GET_EMPLOYEES_LIST_SUCCESSFUL = "GET EMPLOYEES LIST SUCCESSFUL";
export const GET_EMPLOYEES_LIST_ERROR = "GET EMPLOYEES LIST ERROR";

export const GET_EMPLOYEE_DETAIL_REQUEST = "GET EMPLOYEE DETAIL REQUEST";
export const GET_EMPLOYEE_DETAIL_SUCCESSFUL = "GET EMPLOYEE DETAIL SUCCESSFUL";
export const GET_EMPLOYEE_DETAIL_ERROR = "GET EMPLOYEE DETAIL ERROR";

export const ADD_EMPLOYEE_REQUEST = "ADD EMPLOYEE REQUEST";
export const ADD_EMPLOYEE_SUCCESSFUL = "ADD EMPLOYEE SUCCESSFUL";
export const ADD_EMPLOYEE_ERROR = "ADD EMPLOYEE ERROR";

export const UPDATE_EMPLOYEE_REQUEST = "UPDATE EMPLOYEE REQUEST";
export const UPDATE_EMPLOYEE_SUCCESSFUL = "UPDATE EMPLOYEE SUCCESSFUL";
export const UPDATE_EMPLOYEE_ERROR = "UPDATE EMPLOYEE ERROR";

export const DELETE_EMPLOYEE_REQUEST = "DELETE EMPLOYEE REQUEST";
export const DELETE_EMPLOYEE_SUCCESSFUL = "DELETE EMPLOYEE SUCCESSFUL";
export const DELETE_EMPLOYEE_ERROR = "DELETE EMPLOYEE ERROR";
